{"uuid":"c1c72ee8-df64-4750-a2fc-c5cc560db8dc","historyId":"f26bed1319378f23a89d0c42e3f6f1f3","fullName":"com.thetestingacademy.tests.PageObjectModelTests.VWO.TestVWOLogin_03_Retry.testFail","labels":[{"name":"package","value":"com.thetestingacademy.tests.PageObjectModelTests.VWO.TestVWOLogin_03_Retry"},{"name":"testClass","value":"com.thetestingacademy.tests.PageObjectModelTests.VWO.TestVWOLogin_03_Retry"},{"name":"testMethod","value":"testFail"},{"name":"parentSuite","value":"All Test Suite"},{"name":"suite","value":"ATB11xSeleniumAdvanceFramework"},{"name":"subSuite","value":"com.thetestingacademy.tests.PageObjectModelTests.VWO.TestVWOLogin_03_Retry"},{"name":"host","value":"DESKTOP-11LMHML"},{"name":"thread","value":"27684@DESKTOP-11LMHML.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"owner","value":"Vidya"}],"links":[],"name":"testFail","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [true] but found [false]","trace":"java.lang.AssertionError: expected [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1590)\r\n\tat org.testng.Assert.assertTrue(Assert.java:57)\r\n\tat org.testng.Assert.assertTrue(Assert.java:67)\r\n\tat com.thetestingacademy.tests.PageObjectModelTests.VWO.TestVWOLogin_03_Retry.testFail(TestVWOLogin_03_Retry.java:29)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\r\n\tat org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\r\n\tat org.testng.TestRunner.run(TestRunner.java:616)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Verify that invalid creds give error message","steps":[],"attachments":[{"name":"Log output","source":"7bd3beda-fc84-4f57-8e43-27f10e8f19ad-attachment.txt","type":"text/plain"},{"name":"Screenshot","source":"b9830ab7-8a5d-4f09-bf85-bef0e4313d7f-attachment.png","type":"image/png"}],"parameters":[],"start":1755962336525,"stop":1755962342574}